Create a virtual enviroment
`python -m venv .venv`

windows
`source .venv/Scripts/activate`

mac or linux
`source .venv/bin/activate`

install requirements
`pip install requirements.txt`

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import pandas as pd
from pathlib import Path
root = Path(r"C:\Users\ramos\Desktop\GitHub\data-workshop")

data = pd.read_csv(root / "survey lung cancer.csv")

In [3]:
# .describe()

display(data)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [4]:
display(data.isnull().sum())

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

In [5]:
display(data.isna().sum())

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

In [6]:
display(data.head())

display(data.var)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

<bound method DataFrame.var of     GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0        M   69        1               2        2              1
1        M   74        2               1        1              1
2        F   59        1               1        1              2
3        M   63        2               2        2              1
4        F   63        1               2        1              1
..     ...  ...      ...             ...      ...            ...
304      F   56        1               1        1              2
305      M   70        2               1        1              1
306      M   58        2               1        1              1
307      M   67        2               1        2              1
308      M   62        1               1        1              2

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2
1                  2         2         2         1                  1
2                  1         2         1         2                  1
3                  1         1         1         1                  2
4                  1         1         1         2                  1
..               ...       ...       ...       ...                ...
304                2         2         1         1                  2
305                1         2         2         2                  2
306                1         1         2         2                  2
307                1         2         2         1                  2
308                1         2         2         2                  2

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
0           2                    2                      2           2
1           1                    2                      2           2
2           2                    2                      1           2
3           1                    1                      2           2
4           2                    2                      1           1
..        ...                  ...                    ...         ...
304         2                    2                      2           1
305         2                    2                      1           2
306         2                    1                      1           2
307         2                    2                      1           2
308         1                    1                      2           1

    LUNG_CANCER
0           YES
1           YES
2            NO
3            NO
4            NO
..          ...
304         YES
305         YES
306         YES
307         YES
308         YES

[309 rows x 16 columns]>

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
encoder = LabelEncoder()

#encoder.fit(data)
display(data)

#print(data)
# gender, LUNG_CANCER

data["GENDER"] = encoder.fit_transform(data["GENDER"])
data["LUNG_CANCER"] = encoder.fit_transform(data["LUNG_CANCER"])

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [9]:
display(data.head())
display(data["GENDER"].value_counts)
display(data["LUNG_CANCER"].value_counts)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,1,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1
1,1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1
2,0,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0
3,1,63,2,2,2,1,1,1,1,1,2,1,1,2,2,0
4,0,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0

<bound method IndexOpsMixin.value_counts of 0      1
1      1
2      0
3      1
4      0
      ..
304    0
305    1
306    1
307    1
308    1
Name: GENDER, Length: 309, dtype: int64>

<bound method IndexOpsMixin.value_counts of 0      1
1      1
2      0
3      0
4      0
      ..
304    1
305    1
306    1
307    1
308    1
Name: LUNG_CANCER, Length: 309, dtype: int64>

In [10]:
data.var()
#data2 = pd.read_csv(root / "survey lung cancer.csv")
#print(data2)

#data3 = pd.get_dummies(data2 , columns=["GENDER","LUNG_CANCER"]).astype(int)

GENDER                    0.250221
AGE                      67.409049
SMOKING                   0.246816
YELLOW_FINGERS            0.245955
ANXIETY                   0.250809
PEER_PRESSURE             0.250809
CHRONIC DISEASE           0.250788
FATIGUE                   0.220737
ALLERGY                   0.247594
WHEEZING                  0.247594
ALCOHOL CONSUMING         0.247594
COUGHING                  0.244505
SHORTNESS OF BREATH       0.230929
SWALLOWING DIFFICULTY     0.249863
CHEST PAIN                0.247594
LUNG_CANCER               0.110642
dtype: float64

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
print(data.columns)

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'LUNG_CANCER'],
      dtype='object')

In [12]:
X = pd.DataFrame(data,columns=['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH'])

y = pd.DataFrame(data, columns=['LUNG_CANCER'])


train_x, test_x, train_Y, test_Y = train_test_split(X, y, test_size=.3, shuffle=True,random_state=119)

In [ ]:
#print(X.value_counts)
from sklearn.metrics import accuracy_score, classification_report

print(y.value_counts)

model = RandomForestClassifier(n_estimators=100, random_state=119)
#train_x, train_y, test_X, test_Y 
model.fit(train_x, train_Y)


predictions = model.predict(test_x)

y_pred1 = accuracy_score(predictions, test_Y)
y_pred2 = classification_report(predictions, test_Y)

print(y_pred1)
print(y_pred2)

<bound method DataFrame.value_counts of      LUNG_CANCER
0              1
1              1
2              0
3              0
4              0
..           ...
304            1
305            1
306            1
307            1
308            1

[309 rows x 1 columns]>
0.9139784946236559
              precision    recall  f1-score   support

           0       0.70      0.58      0.64        12
           1       0.94      0.96      0.95        81

    accuracy                           0.91        93
   macro avg       0.82      0.77      0.79        93
weighted avg       0.91      0.91      0.91        93

c:\Users\ramos\Desktop\GitHub\data-workshop\.venv\lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)